### ISSUE TITLE
How to reproduce  the specgram function in your PeakFinderDejavu.cpp in Python language?

### ISSUE THREAD

**Issue by xujinchang** [stdio2016/pfa#2]
I have used this code but can't get the same results.
 `samples, sr = sf.read(wavfile)
 arr2D = mlab.specgram(
        samples,
        NFFT=wsize,
        Fs=sr,
        window=signal.windows.hann(wsize),
        noverlap=int(wsize * wratio))[0]
arr2D = 10 * np.log10(arr2D, out=np.zeros_like(arr2D), where=(arr2D != 0))
`

**Comment by xujinchang** [comment]
I have solved it. https://raw.githubusercontent.com/tensorflow/models/master/research/audioset/vggish/mel_features.py

**Comment by stdio2016** [comment]
You can use `tools/repro.py` to reproduce the spectrogram of C++ in Python (please git pull and recompile):
1. Run `./getlm <your WAV file>`. It will save spectrogram as file `temp`.
2. Modify the `wavfile` variable in `tools/repro.py` to your WAV file.
3. Run `python tools/repro.py`.

MP3 file can be used, but even I cannot reproduce the result when audio is MP3 because MP3 is lossy, and MP3 decoder can be compliant even if the result is not bit-exact.
